services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - app-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - app-network
    restart: always

  auth_service:
    build:
      context: .
      dockerfile: auth_service/DockerFile
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    env_file:
    - ./auth_service/.env.development.local
    networks:
      - app-network
    restart: always

  user_service:
    build:
      context: .
      dockerfile: user_service/DockerFile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    env_file:
    - ./user_service/.env.development.local
    networks:
      - app-network
    restart: always

  chat_service:
    build:
      context: .
      dockerfile: chat_service/DockerFile
    ports:
      - "5000:5000"
    env_file:
    - ./chat_service/.env
    networks:
      - app-network
    restart: always

  notification_service:
    build:
      context: .
      dockerfile: notification_service/DockerFile
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
    env_file:
    - ./notification_service/.env
    networks:
      - app-network
    restart: always

  cloud_service:
    build:
      context: .
      dockerfile: cloud-service/DockerFile
    ports:
      - "3000:3000"
    env_file:
    - ./cloud-service/.env
    networks:
      - app-network
    restart: always

  post_service:
    build: 
      context: .
      dockerfile: post_service/DockerFile
    env_file:
      - ./post_service/.env.development.local
    ports:
      - "3006:3006"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge 