# Dùng Node.js nhẹ
FROM node:20-alpine

# Làm việc tại thư mục bên trong container
WORKDIR /app

# Copy package.json và package-lock.json của post_service
COPY post_service/package*.json ./

# Cài dependencies
RUN npm install --production

# Copy toàn bộ mã nguồn của post_service vào containerr
COPY post_service .

# Mở port service
EXPOSE 3006

# Chạy ứng dụng
CMD ["node", "app.js"]
